version: "3.8"

services:
  app:
    build: .
    container_name: name
    ports:
      - "3000:3000"
  productdb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - product-data:/data/db
volumes:
  product-data:
